export class DryItemDemand {
  DryItemDemandID: number;
  DemandDate: number;
  DemandTypeID: number;
  DemandTypeName: string;
  SupplyPlace: number;
  OtherSupplyPlaceName: string;
  FromUnitID: number;
  UnitName: string;
  ToSSDID: number;
  SupplyPlaceID: number;
  GeneralSendReference: string;
  EmergencyDate: Date;
  FoodDemandDate: Date;
  DemandFrom: Date;
  DemandTo: Date;
  PradikarDescription: string;
  Status: number;
  StatusName: string;
  CreatedBy: string;
  CreatedDate: number;
  UpdatedBy: string;
  UpdatedDate: number;
  ApprovedBy: string;
  ApprovedDate: number;
  showApproval: boolean;
  PreviousPradikarNo: string;
  PreviousDemandDate: Date;
  totalDay: number;
  totalResource: number;
  netResource: number
  bellow3ChildTotal: number;
  netChildTotal: number;
  AutogeneratedNumber: string;
  ItemCheck: boolean = false;
  SupplyPlaceName: string;
}