export class POLDemand {
    POLDemandID: number;
    DemandDate: number;
    DemandTypeID: number;
    FromUnitID: number;
    UnitName: string;
    ToSSDID: number;
    SupplyPlaceID: number;
    GeneralSendReference: number;
    Gari: boolean;
    NumberOfGari: number;
    Baral: boolean;
    NumberOfBaral: number;
    Jerican: boolean;
    NumberOfJerican: number;
    GariNumber: string;
    ApprovedBy: number;
    ApprovedDate: number;
    Status: any;
    StatusName: any;
    showApproval: boolean = false;
    AutogeneratedNumber: string;
}

